from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    HealthView,
    SignupView,
    LoginView,
    GoogleLoginView,
    ProfileView,
    DashboardSummaryView,
    ProgressTrackingView,
    WorkoutSessionView,
    CVAnalyzeView,
    VideoWorkoutAnalyzeView,
    WorkoutSummaryView,
    GenerateAIWorkoutPlanView,
    FoodRecognitionView,
    ConsistencyAnalyticsView,
    StreakLeaderboardView,
    SleepLogView,
    FitnessBandSyncView,
    RAGMemoryView,
    ChatAskView,
    RecommendationEngineView,
    WhatsAppBotView,
    ShoppingSuggestionView,
    MusicRecommendationView,
    ProgressPhotoView,
    NotificationPreferenceView,
    AnalyticsOverviewView,
    NutritionLogsView,
    NutritionSearchView,
    NutritionSearchGroqView,
    CartView,
    AddToCartView,
    RemoveFromCartView,
    UpdateCartItemView,
    WikipediaSearchView,
    ShoppingChatView,
    feature_index,
)

urlpatterns = [
    path('health/', HealthView.as_view()),
    path('features/', feature_index),
    path('auth/signup/', SignupView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/google/', GoogleLoginView.as_view()),
    path('auth/token/refresh/', TokenRefreshView.as_view()),
    path('profile/', ProfileView.as_view()),
    path('dashboard/summary/', DashboardSummaryView.as_view()),
    path('dashboard/progress/', ProgressTrackingView.as_view()),
    path('workouts/sessions/', WorkoutSessionView.as_view()),
    path('workouts/ai-plan/', GenerateAIWorkoutPlanView.as_view()),
    path('workouts/cv/analyze/', CVAnalyzeView.as_view()),
    path('workouts/video/analyze/', VideoWorkoutAnalyzeView.as_view()),
    path('workouts/summary/', WorkoutSummaryView.as_view()),
    path('nutrition/recognize/', FoodRecognitionView.as_view()),
    path('analytics/consistency/', ConsistencyAnalyticsView.as_view()),
    path('analytics/streak-leaderboard/', StreakLeaderboardView.as_view()),
    path('analytics/overview/', AnalyticsOverviewView.as_view()),
    path('sleep/logs/', SleepLogView.as_view()),
    path('integrations/bands/sync/', FitnessBandSyncView.as_view()),
    path('rag/memory/', RAGMemoryView.as_view()),
    path('chat/ask/', ChatAskView.as_view()),
    path('recommendations/workout/', RecommendationEngineView.as_view()),
    path('integrations/whatsapp/send/', WhatsAppBotView.as_view()),
    path('shopping/suggestions/', ShoppingSuggestionView.as_view()),
    path('music/recommend/', MusicRecommendationView.as_view()),
    path('progress/photos/', ProgressPhotoView.as_view()),
    path('notifications/preferences/', NotificationPreferenceView.as_view()),
    path('nutrition/logs/', NutritionLogsView.as_view()),
    path('nutrition/search/', NutritionSearchView.as_view()),
    path('nutrition/search/groq/', NutritionSearchGroqView.as_view()),
    path('shopping/cart/', CartView.as_view()),
    path('shopping/cart/add/', AddToCartView.as_view()),
    path('shopping/cart/item/<int:item_id>/', RemoveFromCartView.as_view()),
    path('shopping/cart/item/<int:item_id>/update/', UpdateCartItemView.as_view()),
    path('shopping/wikipedia/search/', WikipediaSearchView.as_view()),
    path('shopping/chat/', ShoppingChatView.as_view()),
]
